version: '3'

services:
  db:
    container_name: mongo
    image: mongo:5
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./datamaster:/data/db
      - ./InitDB/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:      
      MONGO_INITDB_ROOT_USERNAME: sa
      MONGO_INITDB_ROOT_PASSWORD: 123456  
      MONGO_INITDB_DATABASE: nest-pokedex

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: sa
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_MONGODB_URL: mongodb://sa:123456@mongo:27017

      